### ISSUE TITLE
Qui est le lion de Cléopatre ?

### ISSUE THREAD

**Issue by s-i-newton** [ProjetPP/PPP-Spell-Checker#9]
In french, "Qui est le lion de Cléopatre ?" is changed to "Quid est Le lion DE Leopard ?". That's a bit annoying: "qui" is a frequent word in french but "quid" is not. And the other corrections are not really better.

The spellchecker is supposed to handle french, right?

(And we know that the lion of Cleopatra is the king of beasts.)

**Comment by Ezibenroc** [comment]
I tested your sentence with the [demo](https://github.com/ProjetPP/PPP-Spell-Checker/blob/master/demo/demo.py) (and changing the language, [line 12](https://github.com/ProjetPP/PPP-Spell-Checker/blob/master/demo/demo.py#L12)).

The output in English is “Quid est Le lion DE Cleopatra ?”

The output in French is “Qui est le lion de Léopardé ?”

With [askplatyp.us](http://askplatyp.us/?lang=fr&q=Qui+est+le+lion+de+Cl%C3%A9opatre+%3F) there are two outputs: “Quid est Le lion DE Leopard ?” and “Qui est le lion de Léopardé ?”.
The second one is normal, this is the output for French.
`ppp_cli` tells me that the first one also come from the spell-checker, but I am unable to reproduce this on my PC.

**Comment by Tpt** [comment]
The root cause of this issue is maybe a module that outputs the input tagged as in English instead of French. But I haven't found which one does this mess.

**Comment by Tpt** [comment]
This issue as already been fixed by this change: https://github.com/ProjetPP/PPP-Spell-Checker/commit/445844b32330957742ea26666f8b08a5281f49b5

@ProgVal You definitively should deploy the last version of this module.

**Comment by ProgVal** [comment]
I just released a new version of the spell checker.

**Comment by Ezibenroc** [comment]
The problem still [exists](http://askplatyp.us/?lang=fr&q=Qui+est+le+lion+de+Cl%C3%A9opatre+%3F)...

**Comment by ProgVal** [comment]
release != deploy

On 13 février 2015 13:32:42 UTC+01:00, Tom Cornebize <notifications@github.com> wrote:
>The problem still
>[exists](http://askplatyp.us/?lang=fr&q=Qui+est+le+lion+de+Cl%C3%A9opatre+%3F)...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ProjetPP/PPP-Spell-Checker/issues/9#issuecomment-74246968

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
